import defaultTheme from "tailwindcss/defaultTheme";

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php",
        "./storage/framework/views/*.php",
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
    ],
    theme: {
        extend: {
            fontFamily: {
                sans: ["Figtree", ...defaultTheme.fontFamily.sans],
                poppins: ["Poppins", ...defaultTheme.fontFamily.sans],
            },
            colors: {
                blue: {
                    light: "#eecdfd",
                    lightHover: "#e5e3fc",
                    lightActive: "#c9c5f9",
                    normal: "#5043eb",
                    normalHover: "#483cd4",
                    normalActive: "#4036b6",
                    dark: "#3c32b0",
                    darkHover: "#30288d",
                    darkActive: "#241e6a",
                    darker: "#1c1752",
                },
                green: {
                    light: "#e6f6f0",
                    lightHover: "#d9f1e9",
                    lightActive: "#b0e3d1",
                    normal: "#00a56b",
                    normalHover: "#009560",
                    normalActive: "#008458",
                    dark: "#007c50",
                    darkHover: "#006940",
                    darkActive: "#004a30",
                    darker: "#003a25",
                },
                yellow: {
                    light: "#fff9e7",
                    lightHover: "#fff5db",
                    lightActive: "#ffebb5",
                    normal: "#eab54b",
                    normalHover: "#e4a530",
                    normalActive: "#c89028",
                    dark: "#98720b",
                    darkHover: "#725513",
                    darkActive: "#59430b",
                    darker: "#403000",
                },
                red: {
                    light: "#ffdedee",
                    lightHover: "#fce3e6",
                    lightActive: "#fc8c6c",
                    normal: "#e94759",
                    normalHover: "#d24050",
                    normalActive: "#ba3947",
                    dark: "#af3543",
                    darkHover: "#8c2b35",
                    darkActive: "#692028",
                    darker: "#52191f",
                },
                ecstasy: {
                    DEFAULT: "#F97316",
                    50: "#FEDFC9",
                    100: "#FDD3B5",
                    200: "#FCBB8D",
                    300: "#FBA366",
                    400: "#FA8B3E",
                    500: "#F97316",
                    600: "#D25905",
                    700: "#9B4204",
                    800: "#642B03",
                    900: "#2D1301",
                    950: "#120800",
                },
                mainGreen: "#239391",
            },
        },
    },
    plugins: [],
};
